export enum NOTIFICATION_CONTENT_ENUM {
  USER_REQUEST_APPOINTMENT = "USER_REQUEST_APPOINTMENT",
  DOCTOR_ACCEPT_APPOINTMENT = "DOCTOR_ACCEPT_APPOINTMENT",
  DOCTOR_DECLINE_APPOINTMENT = "DOCTOR_DECLINE_APPOINTMENT",
  DOCTOR_CANCEL_APPOINTMENT = "DOCTOR_CANCEL_APPOINTMENT",
  DOCTOR_UPDATE_APPOINTMENT = "DOCTOR_UPDATE_APPOINTMENT",
  DOCTOR_IS_CALLING_YOU = "DOCTOR_IS_CALLING_YOU",
  DOCTOR_ADD_A_CONSULTION = "DOCTOR_ADD_A_CONSULTION",
  DOCTOR_UPDATE_CONSULTION = "DOCTOR_UPDATE_CONSULTION",
}
