export const REMOTE_APP_ROUTING_PREFIX = {
  USER_HOME: "user-home",
  USER_DOCTORS: "user-doctors",
  DOCTOR_DASHBOARD: "doctor-dashboard",
  DOCTOR_APPOINTMENTS: "doctor-appointments",
  VIDEO_CONSULTING: "video-consulting",
  USER_APPOINTMENTS: "user-appointments",
  ADMIN_DOCTORS: "admin-doctors",
  ADMIN_MEDICINES: "admin-medicines",
  ADMIN_TESTS: "admin-tests",
  USER_SETTING: "user-setting",
  DOCTOR_SCHEDULE_TIME: "doctor-schedule-time",
  ADMIN_DASHBOARD: "admin-dashboard",
  ADMIN_PAYMENT: "admin-payment",
  DOCTOR_BLOGS: "doctor-blogs",
  USER_BLOGS: "user-blogs",
};
