export enum permissionMyTimeEnum {
  DELETE_SEAT = 'DELETE_SEAT',
  CREATE_SEAT = 'CREATE_SEAT',
  VIEW_MY_TIME = 'VIEW_MY_TIME',
  VIEW_MY_LEAVE = 'VIEW_MY_LEAVE',
  VIEW_SEAT = 'VIEW_SEAT',
  UPDATE_REQUEST_MANAGEMENT = 'UPDATE_REQUEST_MANAGEMENT',
  VIEW_WORKING_HOUR_ONLYME = 'VIEW_WORKING_HOUR_ONLYME',
  UPDATE_MY_REQUEST = 'UPDATE_MY_REQUEST',
  VIEW_WORKING_HOUR_EVERYONE = 'VIEW_WORKING_HOUR_EVERYONE',
  DELETE_LEAVE = 'DELETE_LEAVE',
  CREATE_LEAVE = 'CREATE_LEAVE',
  UPDATE_LEAVE = 'UPDATE_LEAVE',
  UPDATE_WORKING_HOUR = 'UPDATE_WORKING_HOUR',
  DELETE_MY_REQUEST = 'DELETE_MY_REQUEST',
  CREATE_MY_REQUEST = 'CREATE_MY_REQUEST',
  VIEW_MY_REQUEST = 'VIEW_MY_REQUEST',
  CREATE_WORKING_HOUR = 'CREATE_WORKING_HOUR',
  UPDATE_SEAT = 'UPDATE_SEAT',
  VIEW_REQUEST_MANAGEMENT = 'VIEW_REQUEST_MANAGEMENT'
}
export enum permissionOverviewEnum {
  VIEW_OVERVIEW = 'VIEW_OVERVIEW',
  VIEW_WORKING_HOUR_DETAIL = 'VIEW_WORKING_HOUR_DETAIL',
  VIEW_WORKING_HOUR_EVERYONE = 'VIEW_WORKING_HOUR_EVERYONE'
}
